
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/oficinaApp
    username: koudhi
    password: Mudar123
server:
  error:
    include-stacktrace: never
