spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/pontoApp
    username: koudhi
    password: Mudar123
server:
  error:
    include-stacktrace: never
#    driverClassName: org.postgresql.Driver
